export const mapData = [
  { position: "0", item: "" },
  { position: "1", item: "" },
  { position: "2", item: "" },
  { position: "3", item: "" },
  { position: "4", item: "" },
  { position: "5", item: "" },
  { position: "6", item: "" },
  { position: "7", item: "" },
  { position: "8", item: "" },
  { position: "9", item: "" },
  { position: "10", item: "" },
  { position: "11", item: "" },
  { position: "12", item: "" },
  { position: "13", item: "" },
  { position: "14", item: "" },
  { position: "15", item: "" },
  { position: "16", item: "" },
  { position: "17", item: "" },
  { position: "18", item: "" },
  { position: "19", item: "" },
  { position: "20", item: "" },
  { position: "21", item: "" },
  { position: "22", item: "" },
  { position: "23", item: "" },
  { position: "24", item: "" },
  { position: "25", item: "" },
  { position: "26", item: "" },
  { position: "27", item: "" },
  { position: "28", item: "" },
  { position: "29", item: "" },
  { position: "30", item: "" },
  { position: "31", item: "" },
  { position: "32", item: "" },
  { position: "33", item: "" },
  { position: "34", item: "" },
  { position: "35", item: "" },
  { position: "36", item: "" },
  { position: "37", item: "" },
  { position: "38", item: "" },
  { position: "39", item: "" },
  { position: "40", item: "" },
  { position: "41", item: "" },
  { position: "42", item: "" },
  { position: "43", item: "" },
  { position: "44", item: "" },
  { position: "45", item: "" },
  { position: "46", item: "" },
  { position: "47", item: "" },
  { position: "48", item: "" },
  { position: "49", item: "" },
  { position: "50", item: "" },
  { position: "51", item: "" },
  { position: "B1", item: "" },
  { position: "B2", item: "" },
  { position: "B3", item: "" },
  { position: "B4", item: "" },
  { position: "B5", item: "" },
  { position: "R1", item: "" },
  { position: "R2", item: "" },
  { position: "R3", item: "" },
  { position: "R4", item: "" },
  { position: "R5", item: "" },
  { position: "Y1", item: "" },
  { position: "Y2", item: "" },
  { position: "Y3", item: "" },
  { position: "Y4", item: "" },
  { position: "Y5", item: "" },
  { position: "G1", item: "" },
  { position: "G2", item: "" },
  { position: "G3", item: "" },
  { position: "G4", item: "" },
  { position: "G5", item: "" },
  { position: "red1", item: "RG1" },
  { position: "red2", item: "RG2" },
  { position: "red3", item: "RG3" },
  { position: "red4", item: "RG4" },
  { position: "blue1", item: "BG1" },
  { position: "blue2", item: "BG2" },
  { position: "blue3", item: "BG3" },
  { position: "blue4", item: "BG4" },
  { position: "green1", item: "GG1" },
  { position: "green2", item: "GG2" },
  { position: "green3", item: "GG3" },
  { position: "green4", item: "GG4" },
  { position: "yellow1", item: "YG1" },
  { position: "yellow2", item: "YG2" },
  { position: "yellow3", item: "YG3" },
  { position: "yellow4", item: "YG4" },
];

export type positionDataType = {
  [a: string]: {
    position: string;
    item: string[];
  };
};

export const chanceOrder = { 0: "blue", 1: "yellow", 2: "green", 3: "red" };

export const mapObject: { [a: string]: string } = {
  B: "blue",
  Y: "yellow",
  G: "green",
  R: "red",
};

export const data: positionDataType = {
  0: { position: "0", item: [] },
  1: { position: "1", item: [] },
  2: { position: "2", item: [] },
  3: { position: "3", item: [] },
  4: { position: "4", item: [] },
  5: { position: "5", item: [] },
  6: { position: "6", item: [] },
  7: { position: "7", item: [] },
  8: { position: "8", item: [] },
  9: { position: "9", item: [] },
  10: { position: "10", item: [] },
  11: { position: "11", item: [] },
  12: { position: "12", item: [] },
  13: { position: "13", item: [] },
  14: { position: "14", item: [] },
  15: { position: "15", item: [] },
  16: { position: "16", item: [] },
  17: { position: "17", item: [] },
  18: { position: "18", item: [] },
  19: { position: "19", item: [] },
  20: { position: "20", item: [] },
  21: { position: "21", item: [] },
  22: { position: "22", item: [] },
  23: { position: "23", item: [] },
  24: { position: "24", item: [] },
  25: { position: "25", item: [] },
  26: { position: "26", item: [] },
  27: { position: "27", item: [] },
  28: { position: "28", item: [] },
  29: { position: "29", item: [] },
  30: { position: "30", item: [] },
  31: { position: "31", item: [] },
  32: { position: "32", item: [] },
  33: { position: "33", item: [] },
  34: { position: "34", item: [] },
  35: { position: "35", item: [] },
  36: { position: "36", item: [] },
  37: { position: "37", item: [] },
  38: { position: "38", item: [] },
  39: { position: "39", item: [] },
  40: { position: "40", item: [] },
  41: { position: "41", item: [] },
  42: { position: "42", item: [] },
  43: { position: "43", item: [] },
  44: { position: "44", item: [] },
  45: { position: "45", item: [] },
  46: { position: "46", item: [] },
  47: { position: "47", item: [] },
  48: { position: "48", item: [] },
  49: { position: "49", item: [] },
  50: { position: "50", item: [] },
  51: { position: "51", item: [] },
  CB1: { position: "CB1", item: [] },
  CB2: { position: "CB2", item: [] },
  CB3: { position: "CB3", item: [] },
  CB4: { position: "CB4", item: [] },
  CB5: { position: "CB5", item: [] },
  CR1: { position: "CR1", item: [] },
  CR2: { position: "CR2", item: [] },
  CR3: { position: "CR3", item: [] },
  CR4: { position: "CR4", item: [] },
  CR5: { position: "CR5", item: [] },
  CY1: { position: "CY1", item: [] },
  CY2: { position: "CY2", item: [] },
  CY3: { position: "CY3", item: [] },
  CY4: { position: "CY4", item: [] },
  CY5: { position: "CY5", item: [] },
  CG1: { position: "CG1", item: [] },
  CG2: { position: "CG2", item: [] },
  CG3: { position: "CG3", item: [] },
  CG4: { position: "CG4", item: [] },
  CG5: { position: "CG5", item: [] },
  red1: { position: "red1", item: ["RG1"] },
  red2: { position: "red2", item: ["RG2"] },
  red3: { position: "red3", item: ["RG3"] },
  red4: { position: "red4", item: ["RG4"] },
  blue1: { position: "blue1", item: ["BG1"] },
  blue2: { position: "blue2", item: ["BG2"] },
  blue3: { position: "blue3", item: ["BG3"] },
  blue4: { position: "blue4", item: ["BG4"] },
  green1: { position: "green1", item: ["GG1"] },
  green2: { position: "green2", item: ["GG2"] },
  green3: { position: "green3", item: ["GG3"] },
  green4: { position: "green4", item: ["GG4"] },
  yellow1: { position: "yellow1", item: ["YG1"] },
  yellow2: { position: "yellow2", item: ["YG2"] },
  yellow3: { position: "yellow3", item: ["YG3"] },
  yellow4: { position: "yellow4", item: ["YG4"] },
  win: { position: "win", item: [] },
};
